// packages/angular/src/design-asset-img.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
} from '@angular/core';
import type { AssetCategory } from '@petrvocelka/design-assets-core/names';

import { resolveA11yInputs } from './a11y';
import { DESIGN_ASSETS_CONFIG } from './design-assets-config';
import { resolveAssetImgSrc } from './asset-resolver';

@Component({
  selector: 'design-asset-img',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { '[class]': 'className()' },
  template: `
    <img
      [src]="src()"
      [alt]="a11y().ariaLabel ?? ''"
      [attr.aria-hidden]="a11y().ariaHidden === true ? true : null"
      [attr.width]="width() ?? null"
      [attr.height]="height() ?? null"
      [attr.loading]="loading()"
      [attr.decoding]="decoding()"
    />
  `,
  styles: [`
    :host {
      line-height: 0;
    }

    :host > img {
      display: block;
      max-width: 100%;
      height: auto;
    }
  `],
})
export class DesignAssetImgComponent {
  readonly category = input.required<AssetCategory>();
  readonly name = input.required<string>();
  readonly className = input<string>('', { alias: 'class' });
  readonly decorative = input<boolean | undefined>(undefined);
  readonly ariaLabel = input<string | undefined>(undefined);
  readonly baseUrl = input<string | undefined>(undefined);
  readonly versionTag = input<string | null | undefined>(undefined);
  readonly width = input<number | string | undefined>(undefined);
  readonly height = input<number | string | undefined>(undefined);
  readonly loading = input<'eager' | 'lazy'>('lazy');
  readonly decoding = input<'async' | 'auto' | 'sync'>('async');

  private readonly config = inject(DESIGN_ASSETS_CONFIG);

  protected readonly src = computed(() =>
    resolveAssetImgSrc(
      this.config,
      this.category(),
      this.name(),
      this.baseUrl(),
      this.versionTag(),
    ),
  );

  protected readonly a11y = computed(() =>
    resolveA11yInputs(this.decorative(), this.ariaLabel()),
  );
}

// packages/react/src/design-asset-img.tsx
import type { AssetCategory } from '@petrvocelka/design-assets-core/names';

import { resolveAccessibility, type AccessibleProps } from './external-svg.js';
import {
  type AssetNameForCategory,
  useResolvedAsset,
} from './asset-resolver.js';

export type DesignAssetImgProps<Category extends AssetCategory = AssetCategory> =
  AccessibleProps & {
    category: Category;
    name: AssetNameForCategory<Category>;
    className?: string;
    baseUrl?: string;
    versionTag?: string | null;
    width?: number | string;
    height?: number | string;
    loading?: 'eager' | 'lazy';
    decoding?: 'async' | 'auto' | 'sync';
  };

export function DesignAssetImg<Category extends AssetCategory>({
  category,
  name,
  className,
  baseUrl,
  versionTag,
  width,
  height,
  loading = 'lazy',
  decoding = 'async',
  ...a11y
}: DesignAssetImgProps<Category>) {
  const { src } = useResolvedAsset({ category, name, baseUrl, versionTag });
  const { ariaHidden, ariaLabel } = resolveAccessibility(a11y);

  return (
    <img
      src={src}
      className={className}
      alt={ariaLabel ?? ''}
      aria-hidden={ariaHidden}
      width={width}
      height={height}
      loading={loading}
      decoding={decoding}
    />
  );
}
